# Generated by Django 4.0.3 on 2022-07-25 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listcomment',
            name='is_valid',
            field=models.BooleanField(default=0),
        ),
    ]
