# Generated by Django 4.0.3 on 2022-07-25 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_userinfo_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='kisidetay',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
