# Generated by Django 4.0.3 on 2022-07-25 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_kisidetay_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kisidetay',
            name='surname',
        ),
    ]
