# Generated by Django 4.0.3 on 2022-07-25 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_remove_kisidetay_surname'),
    ]

    operations = [
        migrations.AddField(
            model_name='kisidetay',
            name='surname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
