# Generated by Django 4.0.3 on 2022-07-26 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_kisidetay_images_kisidetay_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=130, null=True)),
                ('card_cvv', models.CharField(blank=True, max_length=3, null=True)),
                ('card_valid_thru', models.CharField(blank=True, max_length=4, null=True)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('cardholder_name', models.CharField(blank=True, max_length=200, null=True)),
                ('card_number', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
