# Generated by Django 4.0.3 on 2022-07-26 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_alter_payment_card_valid_thru'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='card_valid_thru',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
