# Generated by Django 4.0.3 on 2022-07-26 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_rename_subject_contactmodel_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kisidetay',
            name='url',
            field=models.URLField(default='https://twitter.com/home'),
        ),
    ]
