# Generated by Django 4.0.3 on 2022-07-27 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_alter_kisidetay_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactmodel',
            old_name='number',
            new_name='subjects',
        ),
    ]
