# Generated by Django 4.0.3 on 2022-07-27 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_rename_number_contactmodel_subjects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kisidetay',
            name='images',
        ),
        migrations.RemoveField(
            model_name='kisidetay',
            name='url',
        ),
    ]
