# Generated by Django 4.0.3 on 2022-08-01 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_book_delete_qrcodelist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='year',
            field=models.IntegerField(db_column='year', default=2000),
        ),
    ]
