# Generated by Django 4.0.3 on 2022-08-01 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_alter_book_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='year',
            field=models.IntegerField(db_column='year', default=2000, null=True),
        ),
    ]
