# Generated by Django 4.0.3 on 2022-08-01 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_alter_book_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='year',
        ),
    ]
