# Generated by Django 4.0.3 on 2022-07-18 06:55

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('website', '0030_remove_blogbilgi_category_delete_contact_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='blogBilgi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('blog_title', models.CharField(blank=True, max_length=150, null=True)),
                ('blog_description', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
                ('image', models.ImageField(blank=True, default='profile_pics/default.jpg', upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Blog',
            },
        ),
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('subject', models.CharField(blank=True, max_length=150, null=True)),
                ('comments', models.TextField(blank=True, max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='KisiDetay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('surname', models.CharField(blank=True, max_length=200, null=True)),
                ('birth_date', models.DateField(blank=True, max_length=200, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, default='profile_pics/default.jpg', upload_to='')),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='systemImageBilgi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_title', models.CharField(blank=True, max_length=150, null=True)),
                ('banner_link', models.CharField(blank=True, max_length=150, null=True)),
                ('banner_description', ckeditor.fields.RichTextField(blank=True, max_length=1000, null=True)),
                ('image', models.ImageField(blank=True, default='profile_pics/default.jpg', upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Slider',
            },
        ),
    ]
