# Generated by Django 4.0.3 on 2022-07-18 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0032_userinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='userAddPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('il', models.CharField(blank=True, max_length=200, null=True)),
                ('ilce', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, default='profile_pics/default.jpg', upload_to='')),
                ('desc', models.CharField(blank=True, max_length=400, null=True)),
            ],
        ),
    ]
