# Generated by Django 4.0.3 on 2022-07-18 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0035_listcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='listcomment',
            name='comment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
