# Generated by Django 4.0.3 on 2022-07-19 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0036_listcomment_comment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='kisidetay',
            name='desc',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
