# Generated by Django 4.0.3 on 2022-07-19 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0037_kisidetay_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogbilgi',
            name='blog_date',
            field=models.DateField(blank=True, max_length=200, null=True),
        ),
    ]
