# Generated by Django 4.0.3 on 2022-07-21 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0039_alter_blogbilgi_image_alter_kisidetay_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kisidetay',
            options={'verbose_name_plural': 'List'},
        ),
    ]
