# Generated by Django 4.0.3 on 2022-07-21 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0041_kisidetay_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kisidetay',
            options={},
        ),
    ]
