# Generated by Django 4.0.3 on 2022-07-21 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0042_alter_kisidetay_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kisidetay',
            name='slug',
        ),
    ]
