# Generated by Django 4.0.3 on 2022-07-21 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0043_remove_kisidetay_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogbilgi',
            name='blog_description',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
