# Generated by Django 4.0.3 on 2022-07-21 07:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0044_alter_blogbilgi_blog_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogbilgi',
            options={'ordering': ['-created_at', 'blog_title']},
        ),
        migrations.AddField(
            model_name='blogbilgi',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 7, 21, 7, 42, 7, 22422, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
