# Generated by Django 4.0.3 on 2022-07-21 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0045_alter_blogbilgi_options_blogbilgi_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='kisidetay',
            name='adres',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
