# Generated by Django 4.0.3 on 2022-07-21 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0049_kisidetay_death_date_kisidetay_facebook_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogbilgi',
            options={},
        ),
        migrations.RemoveField(
            model_name='blogbilgi',
            name='created_at',
        ),
    ]
